core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Main:index }
 
#Routes d'exercices
sparrow_core_generation:
    path: /urlgeneration
    defaults: { _controller: CoreBundle:Main:generation }

sparrow_core_generated:
    path: /urlgenerated/{id}
    defaults: { _controller: CoreBundle:Main:generated }
    
sparrow_core_antispam:
    path: /antispam
    defaults: { _controller: CoreBundle:Main:antispam }
    
sparrow_core_redirect:
    path: /redirect
    defaults: { _controller: CoreBundle:Main:redirect }
    
sparrow_core_json:
     path: /json
     defaults: { _controller: CoreBundle:Main:json }
   
sparrow_core_course:
    path: /course
    defaults: { _controller: CoreBundle:Main:course } 