sparrow_platform_homepage:
    path:     /
    defaults: { _controller: SparrowPlatformBundle:Default:index }
    
hello_the_world:
    path:     /hello-world
    defaults: { _controller: SparrowPlatformBundle:Advert:index }
    
bye_the_world:
    path:     /bye-world
    defaults: { _controller: SparrowPlatformBundle:Advert:leave }

