sparrow_platform_homepage:
    path:     /
    defaults: { _controller: SparrowPlatformBundle:Default:index }
    
#--------------------------------------------------------------------------------------  
    
sparrow_platform_home:
    path:      /
    defaults: { _controller: SparrowPlatformBundle:Advert:index }
    
sparrow_platform_view:
    path:      /advert/{id}
    defaults: { _controller: SparrowPlatformBundle:Advert:view }
    
sparrow_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults: 
        _controller: SparrowPlatformBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml
    
sparrow_platform_add:
    path:      /add
    defaults: { _controller: SparrowPlatformBundle:Advert:add }
    
#--------------------------------------------------------------------------------------  

hello_the_world:
    path:     /hello-world
    defaults: { _controller: SparrowPlatformBundle:Advert:hello }
    
bye_the_world:
    path:     /bye-world
    defaults: { _controller: SparrowPlatformBundle:Advert:leave }

